-- =====================================================================
-- Playground bootstrap
--
-- Recreates the PostgreSQL schema namespaces over the Parquet exports so
-- that the queries published in docs/08_analysis.md run here unchanged.
-- Without this every query would have to be rewritten to read
-- 'fct_application_2024.parquet' instead of marts.fct_application, and the
-- repository would be shipping two versions of every query.
--
-- The fact view is a UNION ALL over the four year files, which keeps the
-- partition-level file layout that makes the HTTP range requests efficient
-- while presenting one table to the user.
-- =====================================================================
CREATE SCHEMA IF NOT EXISTS marts;
CREATE SCHEMA IF NOT EXISTS ref;

CREATE OR REPLACE VIEW marts.fct_application AS
  SELECT * FROM read_parquet([
    'data/fct_application_2022.parquet',
    'data/fct_application_2023.parquet',
    'data/fct_application_2024.parquet',
    'data/fct_application_2025.parquet']);

CREATE OR REPLACE VIEW marts.dim_date              AS SELECT * FROM 'data/dim_date.parquet';
CREATE OR REPLACE VIEW marts.dim_institution       AS SELECT * FROM 'data/dim_institution.parquet';
CREATE OR REPLACE VIEW marts.dim_tract             AS SELECT * FROM 'data/dim_tract.parquet';
CREATE OR REPLACE VIEW marts.dim_county            AS SELECT * FROM 'data/dim_county.parquet';
CREATE OR REPLACE VIEW marts.dim_msa               AS SELECT * FROM 'data/dim_msa.parquet';
CREATE OR REPLACE VIEW marts.dim_loan_product      AS SELECT * FROM 'data/dim_loan_product.parquet';
CREATE OR REPLACE VIEW marts.dim_dwelling          AS SELECT * FROM 'data/dim_dwelling.parquet';
CREATE OR REPLACE VIEW marts.dim_applicant_profile AS SELECT * FROM 'data/dim_applicant_profile.parquet';

CREATE OR REPLACE VIEW marts.br_application_race      AS SELECT * FROM 'data/br_application_race.parquet';
CREATE OR REPLACE VIEW marts.br_application_ethnicity AS SELECT * FROM 'data/br_application_ethnicity.parquet';
CREATE OR REPLACE VIEW marts.br_denial_reason         AS SELECT * FROM 'data/br_denial_reason.parquet';
CREATE OR REPLACE VIEW marts.br_underwriting_system   AS SELECT * FROM 'data/br_underwriting_system.parquet';
CREATE OR REPLACE VIEW marts.quarantine_application   AS SELECT * FROM 'data/quarantine_application.parquet';

CREATE OR REPLACE VIEW ref.ref_code          AS SELECT * FROM 'data/ref_code.parquet';
CREATE OR REPLACE VIEW ref.assertion_catalog AS SELECT * FROM 'data/assertion_catalog.parquet';

-- The labelled views from migrations/007_views.sql.
--
-- GENERATED by sync_views.py from pg_get_viewdef against the live database.
-- Do not edit between the markers: run sync_views.py instead. The hand-written
-- versions that used to live here had drifted from the real views and nothing
-- caught it, because no published query read from them. See phase 10.

-- >>> GENERATED VIEWS BEGIN (sync_views.py)
CREATE OR REPLACE VIEW marts.v_application AS
SELECT f.activity_year,
       f.application_sk,
       d.source_dataset,
       d.is_provisional,
       i.institution_name,
       i.top_holder_name,
       i.is_minority_owned AS lender_is_minority_owned,
       i.assets_thousands AS lender_assets_thousands,
       i.cra_rating AS lender_cra_rating,
       ra.label AS action_taken,
       pu.label AS loan_purpose,
       lt.label AS loan_type,
       ls.label AS lien_status,
       oc.label AS occupancy_type,
       ap.derived_race AS applicant_race,
       ap.derived_ethnicity AS applicant_ethnicity,
       ap.derived_sex AS applicant_sex,
       ap.applicant_age,
       ap.race_not_reported,
       m.msa_md_name AS msa_name,
       f.county_code,
       f.census_tract,
       t.minority_population_pct AS tract_minority_pct,
       t.tract_to_msa_income_pct,
       f.loan_amount,
       f.income_thousands,
       f.property_value,
       f.interest_rate,
       f.rate_spread,
       f.loan_to_value_ratio,
       f.debt_to_income_band,
       f.total_loan_costs,
       f.is_exempt_filer,
       f.income_na_reason,
       f.ltv_na_reason,
       f.action_taken IN ('1', '3') AS is_decided,
       f.action_taken = '3' AS is_denied,
       f.action_taken = '1' AS is_originated,
       f.action_taken = '5' AS is_closed_incomplete,
       f.action_taken = '4' AS is_withdrawn,
       f.action_taken = '6' AS is_purchased_loan
       FROM marts.fct_application f
       JOIN marts.dim_date d ON d.activity_year = f.activity_year
       JOIN marts.dim_institution i ON i.activity_year = f.activity_year AND i.lei = f.lei
       JOIN marts.dim_tract t ON t.activity_year = f.activity_year AND t.census_tract = f.census_tract
       JOIN marts.dim_msa m ON m.activity_year = f.activity_year AND m.msa_md = f.msa_md
       JOIN marts.dim_loan_product p ON p.loan_product_sk = f.loan_product_sk
       JOIN marts.dim_dwelling w ON w.dwelling_sk = f.dwelling_sk
       JOIN marts.dim_applicant_profile ap ON ap.applicant_profile_sk = f.applicant_profile_sk
       JOIN ref.ref_code ra ON ra.code_field = 'action_taken' AND ra.code_value = f.action_taken
       JOIN ref.ref_code pu ON pu.code_field = 'loan_purpose' AND pu.code_value = p.loan_purpose
       JOIN ref.ref_code lt ON lt.code_field = 'loan_type' AND lt.code_value = p.loan_type
       JOIN ref.ref_code ls ON ls.code_field = 'lien_status' AND ls.code_value = p.lien_status
       JOIN ref.ref_code oc ON oc.code_field = 'occupancy_type' AND oc.code_value = w.occupancy_type;

CREATE OR REPLACE VIEW marts.v_denial_reason AS
SELECT b.activity_year,
       b.application_sk,
       b.reason_ordinal,
       r.label AS denial_reason
       FROM marts.br_denial_reason b
       LEFT JOIN ref.ref_code r ON r.code_field = 'denial_reason_1' AND r.code_value = b.denial_reason_code;

CREATE OR REPLACE VIEW marts.v_application_race AS
SELECT b.activity_year,
       b.application_sk,
       b.party,
       b.slot,
       r.label AS race
       FROM marts.br_application_race b
       LEFT JOIN ref.ref_code r ON r.code_field = 'applicant_race_1' AND r.code_value = b.race_code;
-- <<< GENERATED VIEWS END
